/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Editor,
} from 'brace';


export namespace Components {
  interface StaceEditor {
    'autoUpdateContent': boolean;
    'durationBeforeCallback': number;
    'getEditor': () => Promise<Editor>;
    'mode': string;
    'options': any;
    'readOnly': boolean;
    'text': string;
    'theme': string;
    'timeoutSaving': number;
  }
  interface StaceEditorDemo {}
}

declare global {


  interface HTMLStaceEditorElement extends Components.StaceEditor, HTMLStencilElement {}
  var HTMLStaceEditorElement: {
    prototype: HTMLStaceEditorElement;
    new (): HTMLStaceEditorElement;
  };

  interface HTMLStaceEditorDemoElement extends Components.StaceEditorDemo, HTMLStencilElement {}
  var HTMLStaceEditorDemoElement: {
    prototype: HTMLStaceEditorDemoElement;
    new (): HTMLStaceEditorDemoElement;
  };
  interface HTMLElementTagNameMap {
    'stace-editor': HTMLStaceEditorElement;
    'stace-editor-demo': HTMLStaceEditorDemoElement;
  }
}

declare namespace LocalJSX {
  interface StaceEditor extends JSXBase.HTMLAttributes<HTMLStaceEditorElement> {
    'autoUpdateContent'?: boolean;
    'durationBeforeCallback'?: number;
    'mode'?: string;
    'onTextChange'?: (event: CustomEvent<any>) => void;
    'options'?: any;
    'readOnly'?: boolean;
    'text'?: string;
    'theme'?: string;
    'timeoutSaving'?: number;
  }
  interface StaceEditorDemo extends JSXBase.HTMLAttributes<HTMLStaceEditorDemoElement> {}

  interface IntrinsicElements {
    'stace-editor': StaceEditor;
    'stace-editor-demo': StaceEditorDemo;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


