/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface StaceEditor {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare namespace LocalJSX {
  interface StaceEditor extends JSXBase.HTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'stace-editor': StaceEditor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLStaceEditorElement extends Components.StaceEditor, HTMLStencilElement {}
  var HTMLStaceEditorElement: {
    prototype: HTMLStaceEditorElement;
    new (): HTMLStaceEditorElement;
  };

  interface HTMLElementTagNameMap {
    'stace-editor': HTMLStaceEditorElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

